const menu = { 'combos': [{ 'name': 'Prazeres da Carne', 'description': '1 Espetinho de Alcatra, 1 Espetinho de Filé, Farofa/Vinagrete', 'serves': 2, 'price': 25 }, 
    { 'name': 'Olímpico', 'description': '2 Medalhões de carne, 1 queijo coalho, 1 pão prime', 'serves': 2, 'price': 45 }, 
    { 'name': 'Menos é mais', 'description': '2 Espetinhos mistos com farofa e salada, 1 pão de alho e batata frita', 'serves': 2, 'price': 40 }, 
    { 'name': 'Degustação', 'description': '1 espetinho misto + Filé + Alcatra + Frango, 1 pão de alho e batata frita', 'serves': 2, 'price': 65 }, 
    { 'name': 'Vegetariano', 'description': '2 coalhos, pão de alho e batata frita', 'serves': 2, 'price': 40 }, 
    { 'name': 'Titânico', 'description': '1 Medalhão de cada, 1 pão prime e batata frita', 'serves': 2, 'price': 60 }, 
    { 'name': 'Brazzêro', 'description': '1 espetinho de cada, 2 pães prime, 2 queijos, 2 pães de alho, 2 batatas fritas', 'serves': 4, 'price': 120 }], 
    
    'comidas': [{ 'name': 'Espetinho de Frango', 'description': 'Espetinho de Frango de 100g', 'serves': 1, 'price': 13 }, 
        { 'name': 'Espetinho de Alcatra', 'description': 'Espetinho de Alcatra de 100g', 'serves': 1, 'price': 13 }, 
        { 'name': 'Espetinho de Cupim', 'description': 'Espetinho de Cupim de 100g', 'serves': 1, 'price': 13 }, 
        { 'name': 'Espetinho de Filé', 'description': 'Espetinho de Contra-filé de 100g', 'serves': 1, 'price': 13 }, 
        { 'name': 'Espetinho Misto', 'description': 'Carne + frango + queijo', 'serves': 1, 'price': 13 }, 
        { 'name': 'Medalhão de Frango', 'description': 'Medalhão de frango envolvido com bacon (sem pele) de 150g', 'serves': 1, 'price': 15 }, 
        { 'name': 'Medalhão de Carne', 'description': 'Medalhão de carne envolvido com bacon (sem pele) de 150g', 'serves': 1, 'price': 15 }, 
        { 'name': 'Medalhão Romeu e Julieta', 'description': 'Medalhão de queijo coalho com goiabada envolvida com bacon', 'serves': 1, 'price': 15 }, 
        { 'name': 'Pé Duro', 'description': '1 pão de alho com um churrasco a escolher com vinagrete, molho da casa e queijo maçaricado', 'serves': 1, 'price': 25 }, 
        { 'name': 'Pão Prime', 'description': '1/2 pão de alho com Linguiça Toscana', 'serves': 1, 'price': 10 }, 
        { 'name': 'Pão de Alho', 'description': 'Pão de alho com recheio da casa', 'serves': 1, 'price': 10 }, 
        { 'name': 'Queijo Coalho', 'description': 'Espetinho de queijo coalho com melaço', 'serves': 1, 'price': 10 }, 
        { 'name': 'Batata Frita', 'description': 'Porção com sabor caseiro do Brazzêro', 'serves': 2, 'price': 15 }, 
        { 'name': 'Farofa e Salada', 'description': 'Farofa/Vinagrete com tempero artesanal', 'serves': 1, 'price': 3 }], 
        
    'bebidas': [{ 'name': 'Cerveja em lata', 'description': 'Lata 350ml', 'price': 5 }, 
        { 'name': 'Cerveja Litrinho', 'description': 'Litrinho', 'price': 5 }, 
        { 'name': 'Cerveja LongNeck', 'description': 'Long Neck', 'price': 10 }, 
        { 'name': 'Refrigerante Litro', 'description': 'Refrigerante 1L', 'price': 8 }, 
        { 'name': 'Refrigerante Lata', 'description': 'Lata 350ml', 'price': 5 }, 
        { 'name': 'Água com ou Sem Gás', 'description': 'Garrafa 500ml', 'price': 3 }, 
        { 'name': 'Caipirinha', 'description': 'Cachaça, limão, açúcar, gelo', 'price': 10 }, 
        { 'name': 'Caipiroska', 'description': 'Vodka, limão, açúcar, gelo', 'price': 10 }, 
        { 'name': 'Cuba Libre', 'description': 'Rum, limão, Coca-Cola, gelo', 'price': 10 }, 
        { 'name': 'Daiquiri', 'description': 'Rum, limão, açúcar, gelo', 'price': 10 }, 
    { 'name': 'Daiquiri Red', 'description': 'Rum, morango, açúcar, gelo', 'price': 15 }] };